# Generated by Django 6.0.7 on 2026-09-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('STD', 'Standard'), ('PIO', 'Pioneer'), ('MOD', 'Modern'), ('LEG', 'Legacy'), ('VIN', 'Vintage'), ('PAU', 'Pauper'), ('CMD', 'Commander')], max_length=3)),
                ('colors', models.CharField(help_text='E.g. "RB", "WU", "WUBRG"', max_length=5)),
                ('archetype', models.CharField(choices=[('AGGRO', 'Aggro'), ('MIDRANGE', 'Midrange'), ('CONTROL', 'Control'), ('COMBO', 'Combo'), ('TEMPO', 'Tempo'), ('RAMP', 'Ramp')], max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
