# Generated by Django 6.0.7 on 2026-09-17 16:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_magic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('ONLINE', 'Online (MTGO)'), ('IN_PERSON', 'En persona')], max_length=9)),
                ('play_draw', models.CharField(choices=[('PLAY', 'On the play'), ('DRAW', 'On the draw')], max_length=4)),
                ('result', models.CharField(choices=[('0-0', '0-0'), ('1-0', '1-0'), ('2-0', '2-0'), ('2-1', '2-1'), ('0-1', '0-1'), ('0-2', '0-2'), ('1-2', '1-2'), ('1-1', '1-1')], max_length=3)),
                ('mulligan', models.BooleanField(default=False)),
                ('mulligan_to', models.CharField(blank=True, choices=[('6', '6'), ('5', '5'), ('4', '4'), ('3-', '3 o menos')], max_length=2, null=True)),
                ('played_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='api_magic.deck')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='api_magic.eventtype')),
                ('tags', models.ManyToManyField(blank=True, related_name='matches', to='api_magic.tag')),
            ],
        ),
    ]
