# Generated by Django 6.0.7 on 2026-09-18 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_magic', '0002_eventtype_tag_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='opponent_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_matches', to='api_magic.deck'),
        ),
    ]
