# Generated by Django 6.0.7 on 2026-09-18 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_magic', '0003_match_opponent_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='mulligan',
        ),
        migrations.RemoveField(
            model_name='match',
            name='mulligan_to',
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('winner', models.CharField(choices=[('ME', 'Me'), ('OPPONENT', 'Opponent')], max_length=8)),
                ('mulligan', models.BooleanField(default=False)),
                ('mulligan_to', models.CharField(blank=True, choices=[('6', '6'), ('5', '5'), ('4', '4'), ('3-', '3 o menos')], max_length=2, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='api_magic.match')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
    ]
